name: opuset_dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.2
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.2.0
  - pip>=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.42.0
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pip:
    - -r requirements.txt
